// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.phoenixnap.pulumi.pnap;

import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Optional;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("pnap");
    public Optional<String> clientId() {
        return Codegen.stringProp("clientId").config(config).get();
    }
    public Optional<String> clientSecret() {
        return Codegen.stringProp("clientSecret").config(config).get();
    }
    public Optional<String> configFilePath() {
        return Codegen.stringProp("configFilePath").config(config).get();
    }
}
