// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.phoenixnap.pulumi.pnap;

import com.phoenixnap.pulumi.pnap.inputs.IpBlockTagArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class IpBlockArgs extends com.pulumi.resources.ResourceArgs {

    public static final IpBlockArgs Empty = new IpBlockArgs();

    /**
     * CIDR IP Block Size. Currently this field should be set to either `/31`, `/30`, `/29` or `/28`. For a larger Block Size contact support.
     * 
     */
    @Import(name="cidrBlockSize", required=true)
    private Output<String> cidrBlockSize;

    /**
     * @return CIDR IP Block Size. Currently this field should be set to either `/31`, `/30`, `/29` or `/28`. For a larger Block Size contact support.
     * 
     */
    public Output<String> cidrBlockSize() {
        return this.cidrBlockSize;
    }

    /**
     * Description of the IP Block.
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return Description of the IP Block.
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * IP Block location ID. Currently this field should be set to `PHX`, `ASH`, `SGP`, `NLD`, `CHI`, `SEA` or `AUS`.
     * 
     */
    @Import(name="location", required=true)
    private Output<String> location;

    /**
     * @return IP Block location ID. Currently this field should be set to `PHX`, `ASH`, `SGP`, `NLD`, `CHI`, `SEA` or `AUS`.
     * 
     */
    public Output<String> location() {
        return this.location;
    }

    /**
     * Tags to set to IP Block, if any.
     * 
     */
    @Import(name="tags")
    private @Nullable Output<List<IpBlockTagArgs>> tags;

    /**
     * @return Tags to set to IP Block, if any.
     * 
     */
    public Optional<Output<List<IpBlockTagArgs>>> tags() {
        return Optional.ofNullable(this.tags);
    }

    private IpBlockArgs() {}

    private IpBlockArgs(IpBlockArgs $) {
        this.cidrBlockSize = $.cidrBlockSize;
        this.description = $.description;
        this.location = $.location;
        this.tags = $.tags;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(IpBlockArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private IpBlockArgs $;

        public Builder() {
            $ = new IpBlockArgs();
        }

        public Builder(IpBlockArgs defaults) {
            $ = new IpBlockArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param cidrBlockSize CIDR IP Block Size. Currently this field should be set to either `/31`, `/30`, `/29` or `/28`. For a larger Block Size contact support.
         * 
         * @return builder
         * 
         */
        public Builder cidrBlockSize(Output<String> cidrBlockSize) {
            $.cidrBlockSize = cidrBlockSize;
            return this;
        }

        /**
         * @param cidrBlockSize CIDR IP Block Size. Currently this field should be set to either `/31`, `/30`, `/29` or `/28`. For a larger Block Size contact support.
         * 
         * @return builder
         * 
         */
        public Builder cidrBlockSize(String cidrBlockSize) {
            return cidrBlockSize(Output.of(cidrBlockSize));
        }

        /**
         * @param description Description of the IP Block.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description Description of the IP Block.
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param location IP Block location ID. Currently this field should be set to `PHX`, `ASH`, `SGP`, `NLD`, `CHI`, `SEA` or `AUS`.
         * 
         * @return builder
         * 
         */
        public Builder location(Output<String> location) {
            $.location = location;
            return this;
        }

        /**
         * @param location IP Block location ID. Currently this field should be set to `PHX`, `ASH`, `SGP`, `NLD`, `CHI`, `SEA` or `AUS`.
         * 
         * @return builder
         * 
         */
        public Builder location(String location) {
            return location(Output.of(location));
        }

        /**
         * @param tags Tags to set to IP Block, if any.
         * 
         * @return builder
         * 
         */
        public Builder tags(@Nullable Output<List<IpBlockTagArgs>> tags) {
            $.tags = tags;
            return this;
        }

        /**
         * @param tags Tags to set to IP Block, if any.
         * 
         * @return builder
         * 
         */
        public Builder tags(List<IpBlockTagArgs> tags) {
            return tags(Output.of(tags));
        }

        /**
         * @param tags Tags to set to IP Block, if any.
         * 
         * @return builder
         * 
         */
        public Builder tags(IpBlockTagArgs... tags) {
            return tags(List.of(tags));
        }

        public IpBlockArgs build() {
            if ($.cidrBlockSize == null) {
                throw new MissingRequiredPropertyException("IpBlockArgs", "cidrBlockSize");
            }
            if ($.location == null) {
                throw new MissingRequiredPropertyException("IpBlockArgs", "location");
            }
            return $;
        }
    }

}
