// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.phoenixnap.pulumi.pnap;

import com.phoenixnap.pulumi.pnap.inputs.RancherClusterConfigurationArgs;
import com.phoenixnap.pulumi.pnap.inputs.RancherClusterNodePoolsArgs;
import com.phoenixnap.pulumi.pnap.inputs.RancherClusterWorkloadConfigurationArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RancherClusterArgs extends com.pulumi.resources.ResourceArgs {

    public static final RancherClusterArgs Empty = new RancherClusterArgs();

    /**
     * Rancher configuration parameters. The `configuration` block has 7 fields.
     * 
     */
    @Import(name="configuration")
    private @Nullable Output<RancherClusterConfigurationArgs> configuration;

    /**
     * @return Rancher configuration parameters. The `configuration` block has 7 fields.
     * 
     */
    public Optional<Output<RancherClusterConfigurationArgs>> configuration() {
        return Optional.ofNullable(this.configuration);
    }

    /**
     * Cluster description.
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return Cluster description.
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Workload cluster location. Cannot be changed once the cluster is created. For a full list of allowed locations visit [API docs](https://developers.phoenixnap.com/docs/rancher/1)
     * 
     */
    @Import(name="location", required=true)
    private Output<String> location;

    /**
     * @return Workload cluster location. Cannot be changed once the cluster is created. For a full list of allowed locations visit [API docs](https://developers.phoenixnap.com/docs/rancher/1)
     * 
     */
    public Output<String> location() {
        return this.location;
    }

    /**
     * The name of the workload cluster. This field is autogenerated if not provided.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the workload cluster. This field is autogenerated if not provided.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The node pools associated with the cluster (must contain exactly one item). The `node_pools` block has 4 fields.
     * 
     */
    @Import(name="nodePools")
    private @Nullable Output<RancherClusterNodePoolsArgs> nodePools;

    /**
     * @return The node pools associated with the cluster (must contain exactly one item). The `node_pools` block has 4 fields.
     * 
     */
    public Optional<Output<RancherClusterNodePoolsArgs>> nodePools() {
        return Optional.ofNullable(this.nodePools);
    }

    /**
     * Workload cluster configuration parameters. The `workload_configuration` block has 4 fields.
     * 
     */
    @Import(name="workloadConfiguration")
    private @Nullable Output<RancherClusterWorkloadConfigurationArgs> workloadConfiguration;

    /**
     * @return Workload cluster configuration parameters. The `workload_configuration` block has 4 fields.
     * 
     */
    public Optional<Output<RancherClusterWorkloadConfigurationArgs>> workloadConfiguration() {
        return Optional.ofNullable(this.workloadConfiguration);
    }

    private RancherClusterArgs() {}

    private RancherClusterArgs(RancherClusterArgs $) {
        this.configuration = $.configuration;
        this.description = $.description;
        this.location = $.location;
        this.name = $.name;
        this.nodePools = $.nodePools;
        this.workloadConfiguration = $.workloadConfiguration;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RancherClusterArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RancherClusterArgs $;

        public Builder() {
            $ = new RancherClusterArgs();
        }

        public Builder(RancherClusterArgs defaults) {
            $ = new RancherClusterArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param configuration Rancher configuration parameters. The `configuration` block has 7 fields.
         * 
         * @return builder
         * 
         */
        public Builder configuration(@Nullable Output<RancherClusterConfigurationArgs> configuration) {
            $.configuration = configuration;
            return this;
        }

        /**
         * @param configuration Rancher configuration parameters. The `configuration` block has 7 fields.
         * 
         * @return builder
         * 
         */
        public Builder configuration(RancherClusterConfigurationArgs configuration) {
            return configuration(Output.of(configuration));
        }

        /**
         * @param description Cluster description.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description Cluster description.
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param location Workload cluster location. Cannot be changed once the cluster is created. For a full list of allowed locations visit [API docs](https://developers.phoenixnap.com/docs/rancher/1)
         * 
         * @return builder
         * 
         */
        public Builder location(Output<String> location) {
            $.location = location;
            return this;
        }

        /**
         * @param location Workload cluster location. Cannot be changed once the cluster is created. For a full list of allowed locations visit [API docs](https://developers.phoenixnap.com/docs/rancher/1)
         * 
         * @return builder
         * 
         */
        public Builder location(String location) {
            return location(Output.of(location));
        }

        /**
         * @param name The name of the workload cluster. This field is autogenerated if not provided.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the workload cluster. This field is autogenerated if not provided.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param nodePools The node pools associated with the cluster (must contain exactly one item). The `node_pools` block has 4 fields.
         * 
         * @return builder
         * 
         */
        public Builder nodePools(@Nullable Output<RancherClusterNodePoolsArgs> nodePools) {
            $.nodePools = nodePools;
            return this;
        }

        /**
         * @param nodePools The node pools associated with the cluster (must contain exactly one item). The `node_pools` block has 4 fields.
         * 
         * @return builder
         * 
         */
        public Builder nodePools(RancherClusterNodePoolsArgs nodePools) {
            return nodePools(Output.of(nodePools));
        }

        /**
         * @param workloadConfiguration Workload cluster configuration parameters. The `workload_configuration` block has 4 fields.
         * 
         * @return builder
         * 
         */
        public Builder workloadConfiguration(@Nullable Output<RancherClusterWorkloadConfigurationArgs> workloadConfiguration) {
            $.workloadConfiguration = workloadConfiguration;
            return this;
        }

        /**
         * @param workloadConfiguration Workload cluster configuration parameters. The `workload_configuration` block has 4 fields.
         * 
         * @return builder
         * 
         */
        public Builder workloadConfiguration(RancherClusterWorkloadConfigurationArgs workloadConfiguration) {
            return workloadConfiguration(Output.of(workloadConfiguration));
        }

        public RancherClusterArgs build() {
            if ($.location == null) {
                throw new MissingRequiredPropertyException("RancherClusterArgs", "location");
            }
            return $;
        }
    }

}
