// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pnap

import (
	"context"
	"reflect"

	"github.com/phoenixnap/pulumi-pnap/sdk/go/pnap/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provides a phoenixNAP Public Network datasource. This can be used to read public networks.
//
// ## Example Usage
//
// # Fetch a public network by name and show it's IP Blocks
//
// ```go
// package main
//
// import (
//
//	"github.com/phoenixnap/pulumi-pnap/sdk/go/pnap"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			public_Network_1, err := pnap.LookupPublicNetwork(ctx, &pnap.LookupPublicNetworkArgs{
//				Name: pulumi.StringRef("PubNet1"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("iP-Blocks", public_Network_1.IpBlocks)
//			return nil
//		})
//	}
//
// ```
func LookupPublicNetwork(ctx *pulumi.Context, args *LookupPublicNetworkArgs, opts ...pulumi.InvokeOption) (*LookupPublicNetworkResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupPublicNetworkResult
	err := ctx.Invoke("pnap:index/getPublicNetwork:getPublicNetwork", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPublicNetwork.
type LookupPublicNetworkArgs struct {
	// The public network identifier.
	Id *string `pulumi:"id"`
	// The friendly name of this public network.
	Name *string `pulumi:"name"`
}

// A collection of values returned by getPublicNetwork.
type LookupPublicNetworkResult struct {
	// Date and time when this public network was created.
	CreatedOn string `pulumi:"createdOn"`
	// The description of this public network.
	Description string `pulumi:"description"`
	// The IP Block identifier.
	Id string `pulumi:"id"`
	// A list of IP Blocks that are associated with this public network.
	IpBlocks []GetPublicNetworkIpBlock `pulumi:"ipBlocks"`
	// The location of this public network.
	Location string `pulumi:"location"`
	// A list of resources that are members of this public network.
	Memberships []GetPublicNetworkMembership `pulumi:"memberships"`
	// The friendly name of this public network.
	Name string `pulumi:"name"`
	// The status of the public network.
	Status string `pulumi:"status"`
	VlanId int    `pulumi:"vlanId"`
}

func LookupPublicNetworkOutput(ctx *pulumi.Context, args LookupPublicNetworkOutputArgs, opts ...pulumi.InvokeOption) LookupPublicNetworkResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupPublicNetworkResult, error) {
			args := v.(LookupPublicNetworkArgs)
			r, err := LookupPublicNetwork(ctx, &args, opts...)
			var s LookupPublicNetworkResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupPublicNetworkResultOutput)
}

// A collection of arguments for invoking getPublicNetwork.
type LookupPublicNetworkOutputArgs struct {
	// The public network identifier.
	Id pulumi.StringPtrInput `pulumi:"id"`
	// The friendly name of this public network.
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (LookupPublicNetworkOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupPublicNetworkArgs)(nil)).Elem()
}

// A collection of values returned by getPublicNetwork.
type LookupPublicNetworkResultOutput struct{ *pulumi.OutputState }

func (LookupPublicNetworkResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupPublicNetworkResult)(nil)).Elem()
}

func (o LookupPublicNetworkResultOutput) ToLookupPublicNetworkResultOutput() LookupPublicNetworkResultOutput {
	return o
}

func (o LookupPublicNetworkResultOutput) ToLookupPublicNetworkResultOutputWithContext(ctx context.Context) LookupPublicNetworkResultOutput {
	return o
}

// Date and time when this public network was created.
func (o LookupPublicNetworkResultOutput) CreatedOn() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPublicNetworkResult) string { return v.CreatedOn }).(pulumi.StringOutput)
}

// The description of this public network.
func (o LookupPublicNetworkResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPublicNetworkResult) string { return v.Description }).(pulumi.StringOutput)
}

// The IP Block identifier.
func (o LookupPublicNetworkResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPublicNetworkResult) string { return v.Id }).(pulumi.StringOutput)
}

// A list of IP Blocks that are associated with this public network.
func (o LookupPublicNetworkResultOutput) IpBlocks() GetPublicNetworkIpBlockArrayOutput {
	return o.ApplyT(func(v LookupPublicNetworkResult) []GetPublicNetworkIpBlock { return v.IpBlocks }).(GetPublicNetworkIpBlockArrayOutput)
}

// The location of this public network.
func (o LookupPublicNetworkResultOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPublicNetworkResult) string { return v.Location }).(pulumi.StringOutput)
}

// A list of resources that are members of this public network.
func (o LookupPublicNetworkResultOutput) Memberships() GetPublicNetworkMembershipArrayOutput {
	return o.ApplyT(func(v LookupPublicNetworkResult) []GetPublicNetworkMembership { return v.Memberships }).(GetPublicNetworkMembershipArrayOutput)
}

// The friendly name of this public network.
func (o LookupPublicNetworkResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPublicNetworkResult) string { return v.Name }).(pulumi.StringOutput)
}

// The status of the public network.
func (o LookupPublicNetworkResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPublicNetworkResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o LookupPublicNetworkResultOutput) VlanId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupPublicNetworkResult) int { return v.VlanId }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupPublicNetworkResultOutput{})
}
