// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pnap

import (
	"context"
	"reflect"

	"github.com/phoenixnap/pulumi-pnap/sdk/go/pnap/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provides a phoenixNAP Quota datasource. This can be used to read Quotas.
//
// ## Example Usage
//
// # Fetch a Quota by name and show it's details in alphabetical order
//
// ```go
// package main
//
// import (
//
//	"github.com/phoenixnap/pulumi-pnap/sdk/go/pnap"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			test, err := pnap.GetQuota(ctx, &pnap.GetQuotaArgs{
//				Name: pulumi.StringRef("Public IPs"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("quota", test)
//			return nil
//		})
//	}
//
// ```
func GetQuota(ctx *pulumi.Context, args *GetQuotaArgs, opts ...pulumi.InvokeOption) (*GetQuotaResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetQuotaResult
	err := ctx.Invoke("pnap:index/getQuota:getQuota", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getQuota.
type GetQuotaArgs struct {
	// The ID of the Quota.
	Id *string `pulumi:"id"`
	// The name of the Quota.
	Name *string `pulumi:"name"`
}

// A collection of values returned by getQuota.
type GetQuotaResult struct {
	// The Quota description.
	Description string `pulumi:"description"`
	// The ID of the Quota.
	Id string `pulumi:"id"`
	// The new limit that is requested.
	Limit int `pulumi:"limit"`
	// The name of the Quota.
	Name string `pulumi:"name"`
	// List of requests to change the limit on a Quota.
	QuotaEditLimitRequestDetails []GetQuotaQuotaEditLimitRequestDetail `pulumi:"quotaEditLimitRequestDetails"`
	// The status of the Quota.
	Status string `pulumi:"status"`
	// Unit of the Quota type.
	Unit string `pulumi:"unit"`
	// The Quota used expressed as a number.
	Used int `pulumi:"used"`
}

func GetQuotaOutput(ctx *pulumi.Context, args GetQuotaOutputArgs, opts ...pulumi.InvokeOption) GetQuotaResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetQuotaResult, error) {
			args := v.(GetQuotaArgs)
			r, err := GetQuota(ctx, &args, opts...)
			var s GetQuotaResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetQuotaResultOutput)
}

// A collection of arguments for invoking getQuota.
type GetQuotaOutputArgs struct {
	// The ID of the Quota.
	Id pulumi.StringPtrInput `pulumi:"id"`
	// The name of the Quota.
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (GetQuotaOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetQuotaArgs)(nil)).Elem()
}

// A collection of values returned by getQuota.
type GetQuotaResultOutput struct{ *pulumi.OutputState }

func (GetQuotaResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetQuotaResult)(nil)).Elem()
}

func (o GetQuotaResultOutput) ToGetQuotaResultOutput() GetQuotaResultOutput {
	return o
}

func (o GetQuotaResultOutput) ToGetQuotaResultOutputWithContext(ctx context.Context) GetQuotaResultOutput {
	return o
}

// The Quota description.
func (o GetQuotaResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetQuotaResult) string { return v.Description }).(pulumi.StringOutput)
}

// The ID of the Quota.
func (o GetQuotaResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetQuotaResult) string { return v.Id }).(pulumi.StringOutput)
}

// The new limit that is requested.
func (o GetQuotaResultOutput) Limit() pulumi.IntOutput {
	return o.ApplyT(func(v GetQuotaResult) int { return v.Limit }).(pulumi.IntOutput)
}

// The name of the Quota.
func (o GetQuotaResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetQuotaResult) string { return v.Name }).(pulumi.StringOutput)
}

// List of requests to change the limit on a Quota.
func (o GetQuotaResultOutput) QuotaEditLimitRequestDetails() GetQuotaQuotaEditLimitRequestDetailArrayOutput {
	return o.ApplyT(func(v GetQuotaResult) []GetQuotaQuotaEditLimitRequestDetail { return v.QuotaEditLimitRequestDetails }).(GetQuotaQuotaEditLimitRequestDetailArrayOutput)
}

// The status of the Quota.
func (o GetQuotaResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetQuotaResult) string { return v.Status }).(pulumi.StringOutput)
}

// Unit of the Quota type.
func (o GetQuotaResultOutput) Unit() pulumi.StringOutput {
	return o.ApplyT(func(v GetQuotaResult) string { return v.Unit }).(pulumi.StringOutput)
}

// The Quota used expressed as a number.
func (o GetQuotaResultOutput) Used() pulumi.IntOutput {
	return o.ApplyT(func(v GetQuotaResult) int { return v.Used }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(GetQuotaResultOutput{})
}
