// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.phoenixnap.pulumi.pnap.inputs;

import com.phoenixnap.pulumi.pnap.inputs.GetEventsEventArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.List;
import java.util.Objects;


public final class GetEventsArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetEventsArgs Empty = new GetEventsArgs();

    /**
     * Block `events` has field `name`.
     * 
     */
    @Import(name="events", required=true)
    private Output<List<GetEventsEventArgs>> events;

    /**
     * @return Block `events` has field `name`.
     * 
     */
    public Output<List<GetEventsEventArgs>> events() {
        return this.events;
    }

    private GetEventsArgs() {}

    private GetEventsArgs(GetEventsArgs $) {
        this.events = $.events;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetEventsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetEventsArgs $;

        public Builder() {
            $ = new GetEventsArgs();
        }

        public Builder(GetEventsArgs defaults) {
            $ = new GetEventsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param events Block `events` has field `name`.
         * 
         * @return builder
         * 
         */
        public Builder events(Output<List<GetEventsEventArgs>> events) {
            $.events = events;
            return this;
        }

        /**
         * @param events Block `events` has field `name`.
         * 
         * @return builder
         * 
         */
        public Builder events(List<GetEventsEventArgs> events) {
            return events(Output.of(events));
        }

        /**
         * @param events Block `events` has field `name`.
         * 
         * @return builder
         * 
         */
        public Builder events(GetEventsEventArgs... events) {
            return events(List.of(events));
        }

        public GetEventsArgs build() {
            if ($.events == null) {
                throw new MissingRequiredPropertyException("GetEventsArgs", "events");
            }
            return $;
        }
    }

}
