// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.phoenixnap.pulumi.pnap.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetProductAvailabilityArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetProductAvailabilityArgs Empty = new GetProductAvailabilityArgs();

    /**
     * The location code. Currently the following values are allowed: `PHX`, `ASH`, `NLD`, `SGP`, `CHI`, `SEA` and `AUS`.
     * 
     */
    @Import(name="locations")
    private @Nullable Output<List<String>> locations;

    /**
     * @return The location code. Currently the following values are allowed: `PHX`, `ASH`, `NLD`, `SGP`, `CHI`, `SEA` and `AUS`.
     * 
     */
    public Optional<Output<List<String>>> locations() {
        return Optional.ofNullable(this.locations);
    }

    /**
     * Minimal quantity of product needed. Minimum, maximum and default values might differ for different products. For servers, they are 1, 10 and 1 respectively.
     * 
     */
    @Import(name="minQuantity")
    private @Nullable Output<Double> minQuantity;

    /**
     * @return Minimal quantity of product needed. Minimum, maximum and default values might differ for different products. For servers, they are 1, 10 and 1 respectively.
     * 
     */
    public Optional<Output<Double>> minQuantity() {
        return Optional.ofNullable(this.minQuantity);
    }

    /**
     * Product category. Currently only `SERVER` category is supported.
     * 
     */
    @Import(name="productCategories")
    private @Nullable Output<List<String>> productCategories;

    /**
     * @return Product category. Currently only `SERVER` category is supported.
     * 
     */
    public Optional<Output<List<String>>> productCategories() {
        return Optional.ofNullable(this.productCategories);
    }

    /**
     * The code identifying the product. This code has significance across all locations.
     * 
     */
    @Import(name="productCodes")
    private @Nullable Output<List<String>> productCodes;

    /**
     * @return The code identifying the product. This code has significance across all locations.
     * 
     */
    public Optional<Output<List<String>>> productCodes() {
        return Optional.ofNullable(this.productCodes);
    }

    /**
     * Show only locations where product with requested quantity is available or all locations where product is offered. Default value is `true`.
     * 
     */
    @Import(name="showOnlyMinQuantityAvailable")
    private @Nullable Output<Boolean> showOnlyMinQuantityAvailable;

    /**
     * @return Show only locations where product with requested quantity is available or all locations where product is offered. Default value is `true`.
     * 
     */
    public Optional<Output<Boolean>> showOnlyMinQuantityAvailable() {
        return Optional.ofNullable(this.showOnlyMinQuantityAvailable);
    }

    /**
     * Currently only the following value is allowed: `SERVER_RANCHER`.
     * 
     */
    @Import(name="solutions")
    private @Nullable Output<List<String>> solutions;

    /**
     * @return Currently only the following value is allowed: `SERVER_RANCHER`.
     * 
     */
    public Optional<Output<List<String>>> solutions() {
        return Optional.ofNullable(this.solutions);
    }

    private GetProductAvailabilityArgs() {}

    private GetProductAvailabilityArgs(GetProductAvailabilityArgs $) {
        this.locations = $.locations;
        this.minQuantity = $.minQuantity;
        this.productCategories = $.productCategories;
        this.productCodes = $.productCodes;
        this.showOnlyMinQuantityAvailable = $.showOnlyMinQuantityAvailable;
        this.solutions = $.solutions;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetProductAvailabilityArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetProductAvailabilityArgs $;

        public Builder() {
            $ = new GetProductAvailabilityArgs();
        }

        public Builder(GetProductAvailabilityArgs defaults) {
            $ = new GetProductAvailabilityArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param locations The location code. Currently the following values are allowed: `PHX`, `ASH`, `NLD`, `SGP`, `CHI`, `SEA` and `AUS`.
         * 
         * @return builder
         * 
         */
        public Builder locations(@Nullable Output<List<String>> locations) {
            $.locations = locations;
            return this;
        }

        /**
         * @param locations The location code. Currently the following values are allowed: `PHX`, `ASH`, `NLD`, `SGP`, `CHI`, `SEA` and `AUS`.
         * 
         * @return builder
         * 
         */
        public Builder locations(List<String> locations) {
            return locations(Output.of(locations));
        }

        /**
         * @param locations The location code. Currently the following values are allowed: `PHX`, `ASH`, `NLD`, `SGP`, `CHI`, `SEA` and `AUS`.
         * 
         * @return builder
         * 
         */
        public Builder locations(String... locations) {
            return locations(List.of(locations));
        }

        /**
         * @param minQuantity Minimal quantity of product needed. Minimum, maximum and default values might differ for different products. For servers, they are 1, 10 and 1 respectively.
         * 
         * @return builder
         * 
         */
        public Builder minQuantity(@Nullable Output<Double> minQuantity) {
            $.minQuantity = minQuantity;
            return this;
        }

        /**
         * @param minQuantity Minimal quantity of product needed. Minimum, maximum and default values might differ for different products. For servers, they are 1, 10 and 1 respectively.
         * 
         * @return builder
         * 
         */
        public Builder minQuantity(Double minQuantity) {
            return minQuantity(Output.of(minQuantity));
        }

        /**
         * @param productCategories Product category. Currently only `SERVER` category is supported.
         * 
         * @return builder
         * 
         */
        public Builder productCategories(@Nullable Output<List<String>> productCategories) {
            $.productCategories = productCategories;
            return this;
        }

        /**
         * @param productCategories Product category. Currently only `SERVER` category is supported.
         * 
         * @return builder
         * 
         */
        public Builder productCategories(List<String> productCategories) {
            return productCategories(Output.of(productCategories));
        }

        /**
         * @param productCategories Product category. Currently only `SERVER` category is supported.
         * 
         * @return builder
         * 
         */
        public Builder productCategories(String... productCategories) {
            return productCategories(List.of(productCategories));
        }

        /**
         * @param productCodes The code identifying the product. This code has significance across all locations.
         * 
         * @return builder
         * 
         */
        public Builder productCodes(@Nullable Output<List<String>> productCodes) {
            $.productCodes = productCodes;
            return this;
        }

        /**
         * @param productCodes The code identifying the product. This code has significance across all locations.
         * 
         * @return builder
         * 
         */
        public Builder productCodes(List<String> productCodes) {
            return productCodes(Output.of(productCodes));
        }

        /**
         * @param productCodes The code identifying the product. This code has significance across all locations.
         * 
         * @return builder
         * 
         */
        public Builder productCodes(String... productCodes) {
            return productCodes(List.of(productCodes));
        }

        /**
         * @param showOnlyMinQuantityAvailable Show only locations where product with requested quantity is available or all locations where product is offered. Default value is `true`.
         * 
         * @return builder
         * 
         */
        public Builder showOnlyMinQuantityAvailable(@Nullable Output<Boolean> showOnlyMinQuantityAvailable) {
            $.showOnlyMinQuantityAvailable = showOnlyMinQuantityAvailable;
            return this;
        }

        /**
         * @param showOnlyMinQuantityAvailable Show only locations where product with requested quantity is available or all locations where product is offered. Default value is `true`.
         * 
         * @return builder
         * 
         */
        public Builder showOnlyMinQuantityAvailable(Boolean showOnlyMinQuantityAvailable) {
            return showOnlyMinQuantityAvailable(Output.of(showOnlyMinQuantityAvailable));
        }

        /**
         * @param solutions Currently only the following value is allowed: `SERVER_RANCHER`.
         * 
         * @return builder
         * 
         */
        public Builder solutions(@Nullable Output<List<String>> solutions) {
            $.solutions = solutions;
            return this;
        }

        /**
         * @param solutions Currently only the following value is allowed: `SERVER_RANCHER`.
         * 
         * @return builder
         * 
         */
        public Builder solutions(List<String> solutions) {
            return solutions(Output.of(solutions));
        }

        /**
         * @param solutions Currently only the following value is allowed: `SERVER_RANCHER`.
         * 
         * @return builder
         * 
         */
        public Builder solutions(String... solutions) {
            return solutions(List.of(solutions));
        }

        public GetProductAvailabilityArgs build() {
            return $;
        }
    }

}
