// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.phoenixnap.pulumi.pnap.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetPrivateNetworkPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetPrivateNetworkPlainArgs Empty = new GetPrivateNetworkPlainArgs();

    /**
     * The private network identifier.
     * 
     */
    @Import(name="id")
    private @Nullable String id;

    /**
     * @return The private network identifier.
     * 
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    /**
     * The friendly name of this private network.
     * 
     */
    @Import(name="name")
    private @Nullable String name;

    /**
     * @return The friendly name of this private network.
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    private GetPrivateNetworkPlainArgs() {}

    private GetPrivateNetworkPlainArgs(GetPrivateNetworkPlainArgs $) {
        this.id = $.id;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetPrivateNetworkPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetPrivateNetworkPlainArgs $;

        public Builder() {
            $ = new GetPrivateNetworkPlainArgs();
        }

        public Builder(GetPrivateNetworkPlainArgs defaults) {
            $ = new GetPrivateNetworkPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id The private network identifier.
         * 
         * @return builder
         * 
         */
        public Builder id(@Nullable String id) {
            $.id = id;
            return this;
        }

        /**
         * @param name The friendly name of this private network.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable String name) {
            $.name = name;
            return this;
        }

        public GetPrivateNetworkPlainArgs build() {
            return $;
        }
    }

}
