// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.phoenixnap.pulumi.pnap.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetQuotaPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetQuotaPlainArgs Empty = new GetQuotaPlainArgs();

    /**
     * The ID of the Quota.
     * 
     */
    @Import(name="id")
    private @Nullable String id;

    /**
     * @return The ID of the Quota.
     * 
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    /**
     * The name of the Quota.
     * 
     */
    @Import(name="name")
    private @Nullable String name;

    /**
     * @return The name of the Quota.
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    private GetQuotaPlainArgs() {}

    private GetQuotaPlainArgs(GetQuotaPlainArgs $) {
        this.id = $.id;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetQuotaPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetQuotaPlainArgs $;

        public Builder() {
            $ = new GetQuotaPlainArgs();
        }

        public Builder(GetQuotaPlainArgs defaults) {
            $ = new GetQuotaPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id The ID of the Quota.
         * 
         * @return builder
         * 
         */
        public Builder id(@Nullable String id) {
            $.id = id;
            return this;
        }

        /**
         * @param name The name of the Quota.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable String name) {
            $.name = name;
            return this;
        }

        public GetQuotaPlainArgs build() {
            return $;
        }
    }

}
