// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.phoenixnap.pulumi.pnap.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ServerCloudInitArgs extends com.pulumi.resources.ResourceArgs {

    public static final ServerCloudInitArgs Empty = new ServerCloudInitArgs();

    /**
     * User data for the [cloud-init](https://cloudinit.readthedocs.io/en/latest/) configuration in base64 encoding. NoCloud format is supported. Follow the [instructions](https://phoenixnap.com/kb/bmc-cloud-init) on how to provision a server using cloud-init. Only ubuntu/bionic and ubuntu/focal and ubuntu/jammy are supported.
     * 
     * The `netris_softgate` block has three fields:
     * 
     */
    @Import(name="userData")
    private @Nullable Output<String> userData;

    /**
     * @return User data for the [cloud-init](https://cloudinit.readthedocs.io/en/latest/) configuration in base64 encoding. NoCloud format is supported. Follow the [instructions](https://phoenixnap.com/kb/bmc-cloud-init) on how to provision a server using cloud-init. Only ubuntu/bionic and ubuntu/focal and ubuntu/jammy are supported.
     * 
     * The `netris_softgate` block has three fields:
     * 
     */
    public Optional<Output<String>> userData() {
        return Optional.ofNullable(this.userData);
    }

    private ServerCloudInitArgs() {}

    private ServerCloudInitArgs(ServerCloudInitArgs $) {
        this.userData = $.userData;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ServerCloudInitArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ServerCloudInitArgs $;

        public Builder() {
            $ = new ServerCloudInitArgs();
        }

        public Builder(ServerCloudInitArgs defaults) {
            $ = new ServerCloudInitArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param userData User data for the [cloud-init](https://cloudinit.readthedocs.io/en/latest/) configuration in base64 encoding. NoCloud format is supported. Follow the [instructions](https://phoenixnap.com/kb/bmc-cloud-init) on how to provision a server using cloud-init. Only ubuntu/bionic and ubuntu/focal and ubuntu/jammy are supported.
         * 
         * The `netris_softgate` block has three fields:
         * 
         * @return builder
         * 
         */
        public Builder userData(@Nullable Output<String> userData) {
            $.userData = userData;
            return this;
        }

        /**
         * @param userData User data for the [cloud-init](https://cloudinit.readthedocs.io/en/latest/) configuration in base64 encoding. NoCloud format is supported. Follow the [instructions](https://phoenixnap.com/kb/bmc-cloud-init) on how to provision a server using cloud-init. Only ubuntu/bionic and ubuntu/focal and ubuntu/jammy are supported.
         * 
         * The `netris_softgate` block has three fields:
         * 
         * @return builder
         * 
         */
        public Builder userData(String userData) {
            return userData(Output.of(userData));
        }

        public ServerCloudInitArgs build() {
            return $;
        }
    }

}
