// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PhoenixNAP.Pulumi.Pnap.Inputs
{

    public sealed class IpBlockTagArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Tag request to assign to the IP Block.
        /// </summary>
        [Input("tagAssignment")]
        public Input<Inputs.IpBlockTagTagAssignmentArgs>? TagAssignment { get; set; }

        public IpBlockTagArgs()
        {
        }
        public static new IpBlockTagArgs Empty => new IpBlockTagArgs();
    }
}
