// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PhoenixNAP.Pulumi.Pnap.Inputs
{

    public sealed class StorageNetworkVolumeGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Volume to be created alongside storage.
        /// </summary>
        [Input("volume", required: true)]
        public Input<Inputs.StorageNetworkVolumeVolumeGetArgs> Volume { get; set; } = null!;

        public StorageNetworkVolumeGetArgs()
        {
        }
        public static new StorageNetworkVolumeGetArgs Empty => new StorageNetworkVolumeGetArgs();
    }
}
