# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities
from . import outputs

__all__ = [
    'GetPublicNetworkResult',
    'AwaitableGetPublicNetworkResult',
    'get_public_network',
    'get_public_network_output',
]

@pulumi.output_type
class GetPublicNetworkResult:
    """
    A collection of values returned by getPublicNetwork.
    """
    def __init__(__self__, created_on=None, description=None, id=None, ip_blocks=None, location=None, memberships=None, name=None, status=None, vlan_id=None):
        if created_on and not isinstance(created_on, str):
            raise TypeError("Expected argument 'created_on' to be a str")
        pulumi.set(__self__, "created_on", created_on)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if ip_blocks and not isinstance(ip_blocks, list):
            raise TypeError("Expected argument 'ip_blocks' to be a list")
        pulumi.set(__self__, "ip_blocks", ip_blocks)
        if location and not isinstance(location, str):
            raise TypeError("Expected argument 'location' to be a str")
        pulumi.set(__self__, "location", location)
        if memberships and not isinstance(memberships, list):
            raise TypeError("Expected argument 'memberships' to be a list")
        pulumi.set(__self__, "memberships", memberships)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if status and not isinstance(status, str):
            raise TypeError("Expected argument 'status' to be a str")
        pulumi.set(__self__, "status", status)
        if vlan_id and not isinstance(vlan_id, int):
            raise TypeError("Expected argument 'vlan_id' to be a int")
        pulumi.set(__self__, "vlan_id", vlan_id)

    @property
    @pulumi.getter(name="createdOn")
    def created_on(self) -> str:
        """
        Date and time when this public network was created.
        """
        return pulumi.get(self, "created_on")

    @property
    @pulumi.getter
    def description(self) -> str:
        """
        The description of this public network.
        """
        return pulumi.get(self, "description")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The IP Block identifier.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="ipBlocks")
    def ip_blocks(self) -> Sequence['outputs.GetPublicNetworkIpBlockResult']:
        """
        A list of IP Blocks that are associated with this public network.
        """
        return pulumi.get(self, "ip_blocks")

    @property
    @pulumi.getter
    def location(self) -> str:
        """
        The location of this public network.
        """
        return pulumi.get(self, "location")

    @property
    @pulumi.getter
    def memberships(self) -> Sequence['outputs.GetPublicNetworkMembershipResult']:
        """
        A list of resources that are members of this public network.
        """
        return pulumi.get(self, "memberships")

    @property
    @pulumi.getter
    def name(self) -> str:
        """
        The friendly name of this public network.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def status(self) -> str:
        """
        The status of the public network.
        """
        return pulumi.get(self, "status")

    @property
    @pulumi.getter(name="vlanId")
    def vlan_id(self) -> int:
        return pulumi.get(self, "vlan_id")


class AwaitableGetPublicNetworkResult(GetPublicNetworkResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetPublicNetworkResult(
            created_on=self.created_on,
            description=self.description,
            id=self.id,
            ip_blocks=self.ip_blocks,
            location=self.location,
            memberships=self.memberships,
            name=self.name,
            status=self.status,
            vlan_id=self.vlan_id)


def get_public_network(id: Optional[str] = None,
                       name: Optional[str] = None,
                       opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetPublicNetworkResult:
    """
    Provides a phoenixNAP Public Network datasource. This can be used to read public networks.

    ## Example Usage

    Fetch a public network by name and show it's IP Blocks

    ```python
    import pulumi
    import pulumi_pnap as pnap

    public__network_1 = pnap.get_public_network(name="PubNet1")
    pulumi.export("iP-Blocks", public__network_1.ip_blocks)
    ```


    :param str id: The public network identifier.
    :param str name: The friendly name of this public network.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('pnap:index/getPublicNetwork:getPublicNetwork', __args__, opts=opts, typ=GetPublicNetworkResult).value

    return AwaitableGetPublicNetworkResult(
        created_on=pulumi.get(__ret__, 'created_on'),
        description=pulumi.get(__ret__, 'description'),
        id=pulumi.get(__ret__, 'id'),
        ip_blocks=pulumi.get(__ret__, 'ip_blocks'),
        location=pulumi.get(__ret__, 'location'),
        memberships=pulumi.get(__ret__, 'memberships'),
        name=pulumi.get(__ret__, 'name'),
        status=pulumi.get(__ret__, 'status'),
        vlan_id=pulumi.get(__ret__, 'vlan_id'))


@_utilities.lift_output_func(get_public_network)
def get_public_network_output(id: Optional[pulumi.Input[Optional[str]]] = None,
                              name: Optional[pulumi.Input[Optional[str]]] = None,
                              opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetPublicNetworkResult]:
    """
    Provides a phoenixNAP Public Network datasource. This can be used to read public networks.

    ## Example Usage

    Fetch a public network by name and show it's IP Blocks

    ```python
    import pulumi
    import pulumi_pnap as pnap

    public__network_1 = pnap.get_public_network(name="PubNet1")
    pulumi.export("iP-Blocks", public__network_1.ip_blocks)
    ```


    :param str id: The public network identifier.
    :param str name: The friendly name of this public network.
    """
    ...
