// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PhoenixNAP.Pulumi.Pnap.Outputs
{

    [OutputType]
    public sealed class GetServerNetworkConfigurationResult
    {
        /// <summary>
        /// The address of the gateway assigned to the server.
        /// </summary>
        public readonly string GatewayAddress;
        /// <summary>
        /// IP block details of bare metal server.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetServerNetworkConfigurationIpBlocksConfigurationResult> IpBlocksConfigurations;
        /// <summary>
        /// Private network details of bare metal server.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetServerNetworkConfigurationPrivateNetworkConfigurationResult> PrivateNetworkConfigurations;
        /// <summary>
        /// Public network details of bare metal server.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetServerNetworkConfigurationPublicNetworkConfigurationResult> PublicNetworkConfigurations;

        [OutputConstructor]
        private GetServerNetworkConfigurationResult(
            string gatewayAddress,

            ImmutableArray<Outputs.GetServerNetworkConfigurationIpBlocksConfigurationResult> ipBlocksConfigurations,

            ImmutableArray<Outputs.GetServerNetworkConfigurationPrivateNetworkConfigurationResult> privateNetworkConfigurations,

            ImmutableArray<Outputs.GetServerNetworkConfigurationPublicNetworkConfigurationResult> publicNetworkConfigurations)
        {
            GatewayAddress = gatewayAddress;
            IpBlocksConfigurations = ipBlocksConfigurations;
            PrivateNetworkConfigurations = privateNetworkConfigurations;
            PublicNetworkConfigurations = publicNetworkConfigurations;
        }
    }
}
