// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PhoenixNAP.Pulumi.Pnap.Outputs
{

    [OutputType]
    public sealed class GetServerNetworkConfigurationIpBlocksConfigurationIpBlockResult
    {
        /// <summary>
        /// The unique identifier of the server.
        /// </summary>
        public readonly string Id;
        public readonly int VlanId;

        [OutputConstructor]
        private GetServerNetworkConfigurationIpBlocksConfigurationIpBlockResult(
            string id,

            int vlanId)
        {
            Id = id;
            VlanId = vlanId;
        }
    }
}
