// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PhoenixNAP.Pulumi.Pnap.Outputs
{

    [OutputType]
    public sealed class GetServerStorageConfigurationResult
    {
        /// <summary>
        /// Root partition configuration.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetServerStorageConfigurationRootPartitionResult> RootPartitions;

        [OutputConstructor]
        private GetServerStorageConfigurationResult(ImmutableArray<Outputs.GetServerStorageConfigurationRootPartitionResult> rootPartitions)
        {
            RootPartitions = rootPartitions;
        }
    }
}
