// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PhoenixNAP.Pulumi.Pnap.Outputs
{

    [OutputType]
    public sealed class ServerNetworkConfigurationIpBlocksConfiguration
    {
        /// <summary>
        /// Determines the approach for configuring IP blocks for the server being provisioned. If `PURCHASE_NEW` is selected, the smallest supported range, depending on the operating system, is allocated to the server. The following values are allowed: `PURCHASE_NEW`, `USER_DEFINED`, `NONE`. Default value is `PURCHASE_NEW`.
        /// </summary>
        public readonly string? ConfigurationType;
        /// <summary>
        /// Used to specify the previously purchased IP blocks to assign to this server upon provisioning. Used alongside the `USER_DEFINED` configurationType. Must contain at most 1 item.
        /// 
        /// The `ip_blocks` block has field `server_ip_block`.
        /// The `server_ip_block` block has 2 fields:
        /// </summary>
        public readonly ImmutableArray<Outputs.ServerNetworkConfigurationIpBlocksConfigurationIpBlock> IpBlocks;

        [OutputConstructor]
        private ServerNetworkConfigurationIpBlocksConfiguration(
            string? configurationType,

            ImmutableArray<Outputs.ServerNetworkConfigurationIpBlocksConfigurationIpBlock> ipBlocks)
        {
            ConfigurationType = configurationType;
            IpBlocks = ipBlocks;
        }
    }
}
