// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pnap.Outputs
{

    [OutputType]
    public sealed class GetLocationsLocationProductCategoryResult
    {
        /// <summary>
        /// The product category. Currently the following values are allowed: `SERVER`, `BANDWIDTH`, `OPERATING_SYSTEM`, `PUBLIC_IP` and `STORAGE`.
        /// </summary>
        public readonly string ProductCategory;
        /// <summary>
        /// Description of the product category.
        /// </summary>
        public readonly string ProductCategoryDescription;

        [OutputConstructor]
        private GetLocationsLocationProductCategoryResult(
            string productCategory,

            string productCategoryDescription)
        {
            ProductCategory = productCategory;
            ProductCategoryDescription = productCategoryDescription;
        }
    }
}
