// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pnap.Outputs
{

    [OutputType]
    public sealed class RancherClusterWorkloadConfiguration
    {
        /// <summary>
        /// Workload cluster location. Cannot be changed once the cluster is created. For a full list of allowed locations visit [API docs](https://developers.phoenixnap.com/docs/rancher/1)
        /// </summary>
        public readonly string Location;
        /// <summary>
        /// The name of the workload cluster. This field is autogenerated if not provided.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// Number of configured servers. Currently only server counts of 1 and 3 are possible. Default value is 1.
        /// </summary>
        public readonly int? ServerCount;
        /// <summary>
        /// Node server type. Cannot be changed once the cluster is created. Default value is "s0.d1.small". For a full list of allowed values visit [API docs](https://developers.phoenixnap.com/docs/rancher/1)
        /// </summary>
        public readonly string ServerType;

        [OutputConstructor]
        private RancherClusterWorkloadConfiguration(
            string location,

            string? name,

            int? serverCount,

            string serverType)
        {
            Location = location;
            Name = name;
            ServerCount = serverCount;
            ServerType = serverType;
        }
    }
}
