// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pnap.Outputs
{

    [OutputType]
    public sealed class ServerNetworkConfiguration
    {
        /// <summary>
        /// The address of the gateway assigned / to assign to the server. When used as part of request body, it has to match one of the IP addresses used in the existing assigned private networks for the relevant location. Deprecated in favour of a common gateway address across all networks available under `network_configuration`.
        /// </summary>
        public readonly string? GatewayAddress;
        public readonly Outputs.ServerNetworkConfigurationIpBlocksConfiguration? IpBlocksConfiguration;
        public readonly Outputs.ServerNetworkConfigurationPrivateNetworkConfiguration? PrivateNetworkConfiguration;
        public readonly Outputs.ServerNetworkConfigurationPublicNetworkConfiguration? PublicNetworkConfiguration;

        [OutputConstructor]
        private ServerNetworkConfiguration(
            string? gatewayAddress,

            Outputs.ServerNetworkConfigurationIpBlocksConfiguration? ipBlocksConfiguration,

            Outputs.ServerNetworkConfigurationPrivateNetworkConfiguration? privateNetworkConfiguration,

            Outputs.ServerNetworkConfigurationPublicNetworkConfiguration? publicNetworkConfiguration)
        {
            GatewayAddress = gatewayAddress;
            IpBlocksConfiguration = ipBlocksConfiguration;
            PrivateNetworkConfiguration = privateNetworkConfiguration;
            PublicNetworkConfiguration = publicNetworkConfiguration;
        }
    }
}
