// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pnap.Outputs
{

    [OutputType]
    public sealed class ServerNetworkConfigurationPrivateNetworkConfigurationPrivateNetwork
    {
        public readonly Outputs.ServerNetworkConfigurationPrivateNetworkConfigurationPrivateNetworkServerPrivateNetwork? ServerPrivateNetwork;

        [OutputConstructor]
        private ServerNetworkConfigurationPrivateNetworkConfigurationPrivateNetwork(Outputs.ServerNetworkConfigurationPrivateNetworkConfigurationPrivateNetworkServerPrivateNetwork? serverPrivateNetwork)
        {
            ServerPrivateNetwork = serverPrivateNetwork;
        }
    }
}
