// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pnap.Outputs
{

    [OutputType]
    public sealed class ServerNetworkConfigurationPublicNetworkConfigurationPublicNetworkServerPublicNetwork
    {
        /// <summary>
        /// The network identifier.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// IPs to configure on the server. IPs must be within the network's range. Must contain at least 1 item.
        /// 
        /// 
        /// The `storage_configuration` block has field `root_partition`.
        /// The `root_partition` block has two fields:
        /// </summary>
        public readonly ImmutableArray<string> Ips;
        public readonly string? StatusDescription;

        [OutputConstructor]
        private ServerNetworkConfigurationPublicNetworkConfigurationPublicNetworkServerPublicNetwork(
            string id,

            ImmutableArray<string> ips,

            string? statusDescription)
        {
            Id = id;
            Ips = ips;
            StatusDescription = statusDescription;
        }
    }
}
