// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.phoenixnap.pulumi.pnap.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetEventsEventUserInfo {
    /**
     * @return The BMC account ID.
     * 
     */
    private String accountId;
    /**
     * @return The client ID of the application.
     * 
     */
    private String clientId;
    /**
     * @return The logged in user or owner of the client application.
     * 
     */
    private String username;

    private GetEventsEventUserInfo() {}
    /**
     * @return The BMC account ID.
     * 
     */
    public String accountId() {
        return this.accountId;
    }
    /**
     * @return The client ID of the application.
     * 
     */
    public String clientId() {
        return this.clientId;
    }
    /**
     * @return The logged in user or owner of the client application.
     * 
     */
    public String username() {
        return this.username;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetEventsEventUserInfo defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String accountId;
        private String clientId;
        private String username;
        public Builder() {}
        public Builder(GetEventsEventUserInfo defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accountId = defaults.accountId;
    	      this.clientId = defaults.clientId;
    	      this.username = defaults.username;
        }

        @CustomType.Setter
        public Builder accountId(String accountId) {
            if (accountId == null) {
              throw new MissingRequiredPropertyException("GetEventsEventUserInfo", "accountId");
            }
            this.accountId = accountId;
            return this;
        }
        @CustomType.Setter
        public Builder clientId(String clientId) {
            if (clientId == null) {
              throw new MissingRequiredPropertyException("GetEventsEventUserInfo", "clientId");
            }
            this.clientId = clientId;
            return this;
        }
        @CustomType.Setter
        public Builder username(String username) {
            if (username == null) {
              throw new MissingRequiredPropertyException("GetEventsEventUserInfo", "username");
            }
            this.username = username;
            return this;
        }
        public GetEventsEventUserInfo build() {
            final var _resultValue = new GetEventsEventUserInfo();
            _resultValue.accountId = accountId;
            _resultValue.clientId = clientId;
            _resultValue.username = username;
            return _resultValue;
        }
    }
}
