// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.phoenixnap.pulumi.pnap.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetPublicNetworkMembership {
    /**
     * @return List of public IPs associated to the resource.
     * 
     */
    private List<String> ips;
    /**
     * @return The resource identifier.
     * 
     */
    private String resourceId;
    /**
     * @return The resource&#39;s type.
     * 
     */
    private String resourceType;

    private GetPublicNetworkMembership() {}
    /**
     * @return List of public IPs associated to the resource.
     * 
     */
    public List<String> ips() {
        return this.ips;
    }
    /**
     * @return The resource identifier.
     * 
     */
    public String resourceId() {
        return this.resourceId;
    }
    /**
     * @return The resource&#39;s type.
     * 
     */
    public String resourceType() {
        return this.resourceType;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetPublicNetworkMembership defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<String> ips;
        private String resourceId;
        private String resourceType;
        public Builder() {}
        public Builder(GetPublicNetworkMembership defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.ips = defaults.ips;
    	      this.resourceId = defaults.resourceId;
    	      this.resourceType = defaults.resourceType;
        }

        @CustomType.Setter
        public Builder ips(List<String> ips) {
            if (ips == null) {
              throw new MissingRequiredPropertyException("GetPublicNetworkMembership", "ips");
            }
            this.ips = ips;
            return this;
        }
        public Builder ips(String... ips) {
            return ips(List.of(ips));
        }
        @CustomType.Setter
        public Builder resourceId(String resourceId) {
            if (resourceId == null) {
              throw new MissingRequiredPropertyException("GetPublicNetworkMembership", "resourceId");
            }
            this.resourceId = resourceId;
            return this;
        }
        @CustomType.Setter
        public Builder resourceType(String resourceType) {
            if (resourceType == null) {
              throw new MissingRequiredPropertyException("GetPublicNetworkMembership", "resourceType");
            }
            this.resourceType = resourceType;
            return this;
        }
        public GetPublicNetworkMembership build() {
            final var _resultValue = new GetPublicNetworkMembership();
            _resultValue.ips = ips;
            _resultValue.resourceId = resourceId;
            _resultValue.resourceType = resourceType;
            return _resultValue;
        }
    }
}
