// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.phoenixnap.pulumi.pnap.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetStorageNetworkVolumePermissionNf {
    /**
     * @return All squash permission.
     * 
     */
    private List<String> allSquashes;
    /**
     * @return No squash permission.
     * 
     */
    private List<String> noSquashes;
    /**
     * @return Read only access.
     * 
     */
    private List<String> readOnlies;
    /**
     * @return Read/Write access.
     * 
     */
    private List<String> readWrites;
    /**
     * @return Root squash permission.
     * 
     */
    private List<String> rootSquashes;

    private GetStorageNetworkVolumePermissionNf() {}
    /**
     * @return All squash permission.
     * 
     */
    public List<String> allSquashes() {
        return this.allSquashes;
    }
    /**
     * @return No squash permission.
     * 
     */
    public List<String> noSquashes() {
        return this.noSquashes;
    }
    /**
     * @return Read only access.
     * 
     */
    public List<String> readOnlies() {
        return this.readOnlies;
    }
    /**
     * @return Read/Write access.
     * 
     */
    public List<String> readWrites() {
        return this.readWrites;
    }
    /**
     * @return Root squash permission.
     * 
     */
    public List<String> rootSquashes() {
        return this.rootSquashes;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetStorageNetworkVolumePermissionNf defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<String> allSquashes;
        private List<String> noSquashes;
        private List<String> readOnlies;
        private List<String> readWrites;
        private List<String> rootSquashes;
        public Builder() {}
        public Builder(GetStorageNetworkVolumePermissionNf defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.allSquashes = defaults.allSquashes;
    	      this.noSquashes = defaults.noSquashes;
    	      this.readOnlies = defaults.readOnlies;
    	      this.readWrites = defaults.readWrites;
    	      this.rootSquashes = defaults.rootSquashes;
        }

        @CustomType.Setter
        public Builder allSquashes(List<String> allSquashes) {
            if (allSquashes == null) {
              throw new MissingRequiredPropertyException("GetStorageNetworkVolumePermissionNf", "allSquashes");
            }
            this.allSquashes = allSquashes;
            return this;
        }
        public Builder allSquashes(String... allSquashes) {
            return allSquashes(List.of(allSquashes));
        }
        @CustomType.Setter
        public Builder noSquashes(List<String> noSquashes) {
            if (noSquashes == null) {
              throw new MissingRequiredPropertyException("GetStorageNetworkVolumePermissionNf", "noSquashes");
            }
            this.noSquashes = noSquashes;
            return this;
        }
        public Builder noSquashes(String... noSquashes) {
            return noSquashes(List.of(noSquashes));
        }
        @CustomType.Setter
        public Builder readOnlies(List<String> readOnlies) {
            if (readOnlies == null) {
              throw new MissingRequiredPropertyException("GetStorageNetworkVolumePermissionNf", "readOnlies");
            }
            this.readOnlies = readOnlies;
            return this;
        }
        public Builder readOnlies(String... readOnlies) {
            return readOnlies(List.of(readOnlies));
        }
        @CustomType.Setter
        public Builder readWrites(List<String> readWrites) {
            if (readWrites == null) {
              throw new MissingRequiredPropertyException("GetStorageNetworkVolumePermissionNf", "readWrites");
            }
            this.readWrites = readWrites;
            return this;
        }
        public Builder readWrites(String... readWrites) {
            return readWrites(List.of(readWrites));
        }
        @CustomType.Setter
        public Builder rootSquashes(List<String> rootSquashes) {
            if (rootSquashes == null) {
              throw new MissingRequiredPropertyException("GetStorageNetworkVolumePermissionNf", "rootSquashes");
            }
            this.rootSquashes = rootSquashes;
            return this;
        }
        public Builder rootSquashes(String... rootSquashes) {
            return rootSquashes(List.of(rootSquashes));
        }
        public GetStorageNetworkVolumePermissionNf build() {
            final var _resultValue = new GetStorageNetworkVolumePermissionNf();
            _resultValue.allSquashes = allSquashes;
            _resultValue.noSquashes = noSquashes;
            _resultValue.readOnlies = readOnlies;
            _resultValue.readWrites = readWrites;
            _resultValue.rootSquashes = rootSquashes;
            return _resultValue;
        }
    }
}
