// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.phoenixnap.pulumi.pnap.outputs;

import com.phoenixnap.pulumi.pnap.outputs.GetStorageNetworkVolumePermissionNf;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetStorageNetworkVolumePermission {
    /**
     * @return NFS specific permissions on the volume.
     * 
     */
    private List<GetStorageNetworkVolumePermissionNf> nfs;

    private GetStorageNetworkVolumePermission() {}
    /**
     * @return NFS specific permissions on the volume.
     * 
     */
    public List<GetStorageNetworkVolumePermissionNf> nfs() {
        return this.nfs;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetStorageNetworkVolumePermission defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<GetStorageNetworkVolumePermissionNf> nfs;
        public Builder() {}
        public Builder(GetStorageNetworkVolumePermission defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.nfs = defaults.nfs;
        }

        @CustomType.Setter
        public Builder nfs(List<GetStorageNetworkVolumePermissionNf> nfs) {
            if (nfs == null) {
              throw new MissingRequiredPropertyException("GetStorageNetworkVolumePermission", "nfs");
            }
            this.nfs = nfs;
            return this;
        }
        public Builder nfs(GetStorageNetworkVolumePermissionNf... nfs) {
            return nfs(List.of(nfs));
        }
        public GetStorageNetworkVolumePermission build() {
            final var _resultValue = new GetStorageNetworkVolumePermission();
            _resultValue.nfs = nfs;
            return _resultValue;
        }
    }
}
