// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.phoenixnap.pulumi.pnap.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetServerNetworkConfigurationIpBlocksConfigurationIpBlock {
    /**
     * @return The unique identifier of the server.
     * 
     */
    private String id;
    private Integer vlanId;

    private GetServerNetworkConfigurationIpBlocksConfigurationIpBlock() {}
    /**
     * @return The unique identifier of the server.
     * 
     */
    public String id() {
        return this.id;
    }
    public Integer vlanId() {
        return this.vlanId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetServerNetworkConfigurationIpBlocksConfigurationIpBlock defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private Integer vlanId;
        public Builder() {}
        public Builder(GetServerNetworkConfigurationIpBlocksConfigurationIpBlock defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.vlanId = defaults.vlanId;
        }

        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetServerNetworkConfigurationIpBlocksConfigurationIpBlock", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder vlanId(Integer vlanId) {
            if (vlanId == null) {
              throw new MissingRequiredPropertyException("GetServerNetworkConfigurationIpBlocksConfigurationIpBlock", "vlanId");
            }
            this.vlanId = vlanId;
            return this;
        }
        public GetServerNetworkConfigurationIpBlocksConfigurationIpBlock build() {
            final var _resultValue = new GetServerNetworkConfigurationIpBlocksConfigurationIpBlock();
            _resultValue.id = id;
            _resultValue.vlanId = vlanId;
            return _resultValue;
        }
    }
}
