// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.phoenixnap.pulumi.pnap.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetServerNetworkConfigurationPublicNetworkConfigurationPublicNetwork {
    /**
     * @return The unique identifier of the server.
     * 
     */
    private String id;
    /**
     * @return IPs configured on the server.
     * 
     */
    private List<String> ips;
    /**
     * @return The status of the assignment to the network.
     * 
     */
    private String statusDescription;

    private GetServerNetworkConfigurationPublicNetworkConfigurationPublicNetwork() {}
    /**
     * @return The unique identifier of the server.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return IPs configured on the server.
     * 
     */
    public List<String> ips() {
        return this.ips;
    }
    /**
     * @return The status of the assignment to the network.
     * 
     */
    public String statusDescription() {
        return this.statusDescription;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetServerNetworkConfigurationPublicNetworkConfigurationPublicNetwork defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private List<String> ips;
        private String statusDescription;
        public Builder() {}
        public Builder(GetServerNetworkConfigurationPublicNetworkConfigurationPublicNetwork defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.ips = defaults.ips;
    	      this.statusDescription = defaults.statusDescription;
        }

        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetServerNetworkConfigurationPublicNetworkConfigurationPublicNetwork", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder ips(List<String> ips) {
            if (ips == null) {
              throw new MissingRequiredPropertyException("GetServerNetworkConfigurationPublicNetworkConfigurationPublicNetwork", "ips");
            }
            this.ips = ips;
            return this;
        }
        public Builder ips(String... ips) {
            return ips(List.of(ips));
        }
        @CustomType.Setter
        public Builder statusDescription(String statusDescription) {
            if (statusDescription == null) {
              throw new MissingRequiredPropertyException("GetServerNetworkConfigurationPublicNetworkConfigurationPublicNetwork", "statusDescription");
            }
            this.statusDescription = statusDescription;
            return this;
        }
        public GetServerNetworkConfigurationPublicNetworkConfigurationPublicNetwork build() {
            final var _resultValue = new GetServerNetworkConfigurationPublicNetworkConfigurationPublicNetwork();
            _resultValue.id = id;
            _resultValue.ips = ips;
            _resultValue.statusDescription = statusDescription;
            return _resultValue;
        }
    }
}
