// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.phoenixnap.pulumi.pnap.outputs;

import com.phoenixnap.pulumi.pnap.outputs.GetServerNetworkConfigurationIpBlocksConfiguration;
import com.phoenixnap.pulumi.pnap.outputs.GetServerNetworkConfigurationPrivateNetworkConfiguration;
import com.phoenixnap.pulumi.pnap.outputs.GetServerNetworkConfigurationPublicNetworkConfiguration;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetServerNetworkConfiguration {
    /**
     * @return The address of the gateway assigned to the server.
     * 
     */
    private String gatewayAddress;
    /**
     * @return IP block details of bare metal server.
     * 
     */
    private List<GetServerNetworkConfigurationIpBlocksConfiguration> ipBlocksConfigurations;
    /**
     * @return Private network details of bare metal server.
     * 
     */
    private List<GetServerNetworkConfigurationPrivateNetworkConfiguration> privateNetworkConfigurations;
    /**
     * @return Public network details of bare metal server.
     * 
     */
    private List<GetServerNetworkConfigurationPublicNetworkConfiguration> publicNetworkConfigurations;

    private GetServerNetworkConfiguration() {}
    /**
     * @return The address of the gateway assigned to the server.
     * 
     */
    public String gatewayAddress() {
        return this.gatewayAddress;
    }
    /**
     * @return IP block details of bare metal server.
     * 
     */
    public List<GetServerNetworkConfigurationIpBlocksConfiguration> ipBlocksConfigurations() {
        return this.ipBlocksConfigurations;
    }
    /**
     * @return Private network details of bare metal server.
     * 
     */
    public List<GetServerNetworkConfigurationPrivateNetworkConfiguration> privateNetworkConfigurations() {
        return this.privateNetworkConfigurations;
    }
    /**
     * @return Public network details of bare metal server.
     * 
     */
    public List<GetServerNetworkConfigurationPublicNetworkConfiguration> publicNetworkConfigurations() {
        return this.publicNetworkConfigurations;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetServerNetworkConfiguration defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String gatewayAddress;
        private List<GetServerNetworkConfigurationIpBlocksConfiguration> ipBlocksConfigurations;
        private List<GetServerNetworkConfigurationPrivateNetworkConfiguration> privateNetworkConfigurations;
        private List<GetServerNetworkConfigurationPublicNetworkConfiguration> publicNetworkConfigurations;
        public Builder() {}
        public Builder(GetServerNetworkConfiguration defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.gatewayAddress = defaults.gatewayAddress;
    	      this.ipBlocksConfigurations = defaults.ipBlocksConfigurations;
    	      this.privateNetworkConfigurations = defaults.privateNetworkConfigurations;
    	      this.publicNetworkConfigurations = defaults.publicNetworkConfigurations;
        }

        @CustomType.Setter
        public Builder gatewayAddress(String gatewayAddress) {
            if (gatewayAddress == null) {
              throw new MissingRequiredPropertyException("GetServerNetworkConfiguration", "gatewayAddress");
            }
            this.gatewayAddress = gatewayAddress;
            return this;
        }
        @CustomType.Setter
        public Builder ipBlocksConfigurations(List<GetServerNetworkConfigurationIpBlocksConfiguration> ipBlocksConfigurations) {
            if (ipBlocksConfigurations == null) {
              throw new MissingRequiredPropertyException("GetServerNetworkConfiguration", "ipBlocksConfigurations");
            }
            this.ipBlocksConfigurations = ipBlocksConfigurations;
            return this;
        }
        public Builder ipBlocksConfigurations(GetServerNetworkConfigurationIpBlocksConfiguration... ipBlocksConfigurations) {
            return ipBlocksConfigurations(List.of(ipBlocksConfigurations));
        }
        @CustomType.Setter
        public Builder privateNetworkConfigurations(List<GetServerNetworkConfigurationPrivateNetworkConfiguration> privateNetworkConfigurations) {
            if (privateNetworkConfigurations == null) {
              throw new MissingRequiredPropertyException("GetServerNetworkConfiguration", "privateNetworkConfigurations");
            }
            this.privateNetworkConfigurations = privateNetworkConfigurations;
            return this;
        }
        public Builder privateNetworkConfigurations(GetServerNetworkConfigurationPrivateNetworkConfiguration... privateNetworkConfigurations) {
            return privateNetworkConfigurations(List.of(privateNetworkConfigurations));
        }
        @CustomType.Setter
        public Builder publicNetworkConfigurations(List<GetServerNetworkConfigurationPublicNetworkConfiguration> publicNetworkConfigurations) {
            if (publicNetworkConfigurations == null) {
              throw new MissingRequiredPropertyException("GetServerNetworkConfiguration", "publicNetworkConfigurations");
            }
            this.publicNetworkConfigurations = publicNetworkConfigurations;
            return this;
        }
        public Builder publicNetworkConfigurations(GetServerNetworkConfigurationPublicNetworkConfiguration... publicNetworkConfigurations) {
            return publicNetworkConfigurations(List.of(publicNetworkConfigurations));
        }
        public GetServerNetworkConfiguration build() {
            final var _resultValue = new GetServerNetworkConfiguration();
            _resultValue.gatewayAddress = gatewayAddress;
            _resultValue.ipBlocksConfigurations = ipBlocksConfigurations;
            _resultValue.privateNetworkConfigurations = privateNetworkConfigurations;
            _resultValue.publicNetworkConfigurations = publicNetworkConfigurations;
            return _resultValue;
        }
    }
}
