// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.phoenixnap.pulumi.pnap.outputs;

import com.phoenixnap.pulumi.pnap.outputs.GetTagResourceAssignment;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetTagResult {
    private String createdBy;
    /**
     * @return The description of the tag.
     * * ` is_billing_tag  `- Whether or not to show the tag as part of billing and invoices.
     * * ` resource_assignments  ` - The tag&#39;s assigned resources.
     * 
     */
    private String description;
    /**
     * @return The unique identifier of the tag.
     * 
     */
    private String id;
    private Boolean isBillingTag;
    /**
     * @return The name of the tag.
     * 
     */
    private String name;
    private List<GetTagResourceAssignment> resourceAssignments;
    /**
     * @return The optional values of the tag..
     * 
     */
    private List<String> values;

    private GetTagResult() {}
    public String createdBy() {
        return this.createdBy;
    }
    /**
     * @return The description of the tag.
     * * ` is_billing_tag  `- Whether or not to show the tag as part of billing and invoices.
     * * ` resource_assignments  ` - The tag&#39;s assigned resources.
     * 
     */
    public String description() {
        return this.description;
    }
    /**
     * @return The unique identifier of the tag.
     * 
     */
    public String id() {
        return this.id;
    }
    public Boolean isBillingTag() {
        return this.isBillingTag;
    }
    /**
     * @return The name of the tag.
     * 
     */
    public String name() {
        return this.name;
    }
    public List<GetTagResourceAssignment> resourceAssignments() {
        return this.resourceAssignments;
    }
    /**
     * @return The optional values of the tag..
     * 
     */
    public List<String> values() {
        return this.values;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetTagResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String createdBy;
        private String description;
        private String id;
        private Boolean isBillingTag;
        private String name;
        private List<GetTagResourceAssignment> resourceAssignments;
        private List<String> values;
        public Builder() {}
        public Builder(GetTagResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.createdBy = defaults.createdBy;
    	      this.description = defaults.description;
    	      this.id = defaults.id;
    	      this.isBillingTag = defaults.isBillingTag;
    	      this.name = defaults.name;
    	      this.resourceAssignments = defaults.resourceAssignments;
    	      this.values = defaults.values;
        }

        @CustomType.Setter
        public Builder createdBy(String createdBy) {
            if (createdBy == null) {
              throw new MissingRequiredPropertyException("GetTagResult", "createdBy");
            }
            this.createdBy = createdBy;
            return this;
        }
        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetTagResult", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetTagResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder isBillingTag(Boolean isBillingTag) {
            if (isBillingTag == null) {
              throw new MissingRequiredPropertyException("GetTagResult", "isBillingTag");
            }
            this.isBillingTag = isBillingTag;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetTagResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder resourceAssignments(List<GetTagResourceAssignment> resourceAssignments) {
            if (resourceAssignments == null) {
              throw new MissingRequiredPropertyException("GetTagResult", "resourceAssignments");
            }
            this.resourceAssignments = resourceAssignments;
            return this;
        }
        public Builder resourceAssignments(GetTagResourceAssignment... resourceAssignments) {
            return resourceAssignments(List.of(resourceAssignments));
        }
        @CustomType.Setter
        public Builder values(List<String> values) {
            if (values == null) {
              throw new MissingRequiredPropertyException("GetTagResult", "values");
            }
            this.values = values;
            return this;
        }
        public Builder values(String... values) {
            return values(List.of(values));
        }
        public GetTagResult build() {
            final var _resultValue = new GetTagResult();
            _resultValue.createdBy = createdBy;
            _resultValue.description = description;
            _resultValue.id = id;
            _resultValue.isBillingTag = isBillingTag;
            _resultValue.name = name;
            _resultValue.resourceAssignments = resourceAssignments;
            _resultValue.values = values;
            return _resultValue;
        }
    }
}
