// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.phoenixnap.pulumi.pnap.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class RancherClusterNodePoolsSshConfig {
    /**
     * @return Define whether public keys marked as default should be installed on this node. Default value is true.
     * 
     */
    private @Nullable Boolean installDefaultKeys;
    /**
     * @return List of public SSH key identifiers.
     * 
     */
    private @Nullable List<String> keyIds;
    /**
     * @return List of public SSH keys.
     * 
     */
    private @Nullable List<String> keys;

    private RancherClusterNodePoolsSshConfig() {}
    /**
     * @return Define whether public keys marked as default should be installed on this node. Default value is true.
     * 
     */
    public Optional<Boolean> installDefaultKeys() {
        return Optional.ofNullable(this.installDefaultKeys);
    }
    /**
     * @return List of public SSH key identifiers.
     * 
     */
    public List<String> keyIds() {
        return this.keyIds == null ? List.of() : this.keyIds;
    }
    /**
     * @return List of public SSH keys.
     * 
     */
    public List<String> keys() {
        return this.keys == null ? List.of() : this.keys;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(RancherClusterNodePoolsSshConfig defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean installDefaultKeys;
        private @Nullable List<String> keyIds;
        private @Nullable List<String> keys;
        public Builder() {}
        public Builder(RancherClusterNodePoolsSshConfig defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.installDefaultKeys = defaults.installDefaultKeys;
    	      this.keyIds = defaults.keyIds;
    	      this.keys = defaults.keys;
        }

        @CustomType.Setter
        public Builder installDefaultKeys(@Nullable Boolean installDefaultKeys) {

            this.installDefaultKeys = installDefaultKeys;
            return this;
        }
        @CustomType.Setter
        public Builder keyIds(@Nullable List<String> keyIds) {

            this.keyIds = keyIds;
            return this;
        }
        public Builder keyIds(String... keyIds) {
            return keyIds(List.of(keyIds));
        }
        @CustomType.Setter
        public Builder keys(@Nullable List<String> keys) {

            this.keys = keys;
            return this;
        }
        public Builder keys(String... keys) {
            return keys(List.of(keys));
        }
        public RancherClusterNodePoolsSshConfig build() {
            final var _resultValue = new RancherClusterNodePoolsSshConfig();
            _resultValue.installDefaultKeys = installDefaultKeys;
            _resultValue.keyIds = keyIds;
            _resultValue.keys = keys;
            return _resultValue;
        }
    }
}
