// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.phoenixnap.pulumi.pnap.outputs;

import com.phoenixnap.pulumi.pnap.outputs.ServerNetworkConfigurationPublicNetworkConfigurationPublicNetworkServerPublicNetwork;
import com.pulumi.core.annotations.CustomType;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ServerNetworkConfigurationPublicNetworkConfigurationPublicNetwork {
    private @Nullable ServerNetworkConfigurationPublicNetworkConfigurationPublicNetworkServerPublicNetwork serverPublicNetwork;

    private ServerNetworkConfigurationPublicNetworkConfigurationPublicNetwork() {}
    public Optional<ServerNetworkConfigurationPublicNetworkConfigurationPublicNetworkServerPublicNetwork> serverPublicNetwork() {
        return Optional.ofNullable(this.serverPublicNetwork);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ServerNetworkConfigurationPublicNetworkConfigurationPublicNetwork defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable ServerNetworkConfigurationPublicNetworkConfigurationPublicNetworkServerPublicNetwork serverPublicNetwork;
        public Builder() {}
        public Builder(ServerNetworkConfigurationPublicNetworkConfigurationPublicNetwork defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.serverPublicNetwork = defaults.serverPublicNetwork;
        }

        @CustomType.Setter
        public Builder serverPublicNetwork(@Nullable ServerNetworkConfigurationPublicNetworkConfigurationPublicNetworkServerPublicNetwork serverPublicNetwork) {

            this.serverPublicNetwork = serverPublicNetwork;
            return this;
        }
        public ServerNetworkConfigurationPublicNetworkConfigurationPublicNetwork build() {
            final var _resultValue = new ServerNetworkConfigurationPublicNetworkConfigurationPublicNetwork();
            _resultValue.serverPublicNetwork = serverPublicNetwork;
            return _resultValue;
        }
    }
}
