// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.phoenixnap.pulumi.pnap.outputs;

import com.phoenixnap.pulumi.pnap.outputs.StorageNetworkVolumeVolumePermissionNf;
import com.pulumi.core.annotations.CustomType;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class StorageNetworkVolumeVolumePermission {
    /**
     * @return NFS specific permissions on the volume.
     * 
     */
    private @Nullable List<StorageNetworkVolumeVolumePermissionNf> nfs;

    private StorageNetworkVolumeVolumePermission() {}
    /**
     * @return NFS specific permissions on the volume.
     * 
     */
    public List<StorageNetworkVolumeVolumePermissionNf> nfs() {
        return this.nfs == null ? List.of() : this.nfs;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(StorageNetworkVolumeVolumePermission defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<StorageNetworkVolumeVolumePermissionNf> nfs;
        public Builder() {}
        public Builder(StorageNetworkVolumeVolumePermission defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.nfs = defaults.nfs;
        }

        @CustomType.Setter
        public Builder nfs(@Nullable List<StorageNetworkVolumeVolumePermissionNf> nfs) {

            this.nfs = nfs;
            return this;
        }
        public Builder nfs(StorageNetworkVolumeVolumePermissionNf... nfs) {
            return nfs(List.of(nfs));
        }
        public StorageNetworkVolumeVolumePermission build() {
            final var _resultValue = new StorageNetworkVolumeVolumePermission();
            _resultValue.nfs = nfs;
            return _resultValue;
        }
    }
}
