// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provides a phoenixNAP locations datasource. This can be used to retrieve locations info.
 *
 * ## Example Usage
 *
 * Fetch locations by product category and show their details.
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as pnap from "@pulumi/pnap";
 *
 * const query-C = pnap.getLocations({
 *     productCategory: "BANDWIDTH",
 * });
 * export const locations = query_C.then(query_C => query_C.locations);
 * ```
 */
export function getLocations(args?: GetLocationsArgs, opts?: pulumi.InvokeOptions): Promise<GetLocationsResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("pnap:index/getLocations:getLocations", {
        "location": args.location,
        "productCategory": args.productCategory,
    }, opts);
}

/**
 * A collection of arguments for invoking getLocations.
 */
export interface GetLocationsArgs {
    /**
     * The location code. Currently the following values are allowed: `PHX`, `ASH`, `NLD`, `SGP`, `CHI`, `SEA` and `AUS`.
     */
    location?: string;
    /**
     * The product category. Currently the following values are allowed: `SERVER`, `BANDWIDTH`, `OPERATING_SYSTEM`, `PUBLIC_IP` and `STORAGE`.
     */
    productCategory?: string;
}

/**
 * A collection of values returned by getLocations.
 */
export interface GetLocationsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The location code.
     */
    readonly location?: string;
    /**
     * The list of locations found.
     */
    readonly locations: outputs.GetLocationsLocation[];
    /**
     * The product category.
     */
    readonly productCategory?: string;
}
/**
 * Provides a phoenixNAP locations datasource. This can be used to retrieve locations info.
 *
 * ## Example Usage
 *
 * Fetch locations by product category and show their details.
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as pnap from "@pulumi/pnap";
 *
 * const query-C = pnap.getLocations({
 *     productCategory: "BANDWIDTH",
 * });
 * export const locations = query_C.then(query_C => query_C.locations);
 * ```
 */
export function getLocationsOutput(args?: GetLocationsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetLocationsResult> {
    return pulumi.output(args).apply((a: any) => getLocations(a, opts))
}

/**
 * A collection of arguments for invoking getLocations.
 */
export interface GetLocationsOutputArgs {
    /**
     * The location code. Currently the following values are allowed: `PHX`, `ASH`, `NLD`, `SGP`, `CHI`, `SEA` and `AUS`.
     */
    location?: pulumi.Input<string>;
    /**
     * The product category. Currently the following values are allowed: `SERVER`, `BANDWIDTH`, `OPERATING_SYSTEM`, `PUBLIC_IP` and `STORAGE`.
     */
    productCategory?: pulumi.Input<string>;
}
